<!DOCTYPE html>
<html lang="en">
  <?php
    $title = "Privacy policy";
    require ("inc/head.php");
  ?>
  <body>
  	<?php include 'inc/header.php' ?>
  	<section id="legal">
      <div class="legal-container">
        <div class="title">
          <h2>Privacy policy</h2>
        </div>
        <div class="legal-text">
          <p>nefertarigirls.com believes in protecting your privacy. This Privacy Policy sets out how we will treat the personal information which you provide to us while using the website located at www.nefertarigirls.com (the "Site") and/or the services provided from it (the "Services"). Please read this Privacy Policy carefully and know that we do not sell, share or rent personal information to third parties without your consent, except in specific cases described below or unless we are required to do so by law.</p>
          <p>- Your use of the Site means that you have accepted this Privacy Policy. If you are unwilling to be bound by some of the clauses then please do not use the Site. If you register as a User of the Site, or submit personally identifiable information, this indicates that you have read and understood this Privacy Policy and you agreed to its contents.</p>
          <p>- We may change this Privacy Policy from time to time and such changes will take effect from the date and time the revised Privacy Policy is available on the Site. Please regularly visit the Privacy Policy so that you are aware of any modifications or updates. Your continued use of the Site means that you have accepted any modifications or amends.</p>
          <p>- To provide the Site and the Services, it is necessary for us to hold and process certain personal information about you including, but not limited to, your name, gender, age, contact details and email address. You agree to us collecting this personal information. We take reasonable care in keeping this information secure and preventing any unauthorised access or unlawful use of it. All personal information is processed by us in accordance with applicable data protection legislation.</p>
          <p>- From time to time, we may ask you to provide some or all of the following: details of your name, your company number and/or trading name, address, telephone/facsimile number(s), e-mail address and credit card or other details. This personal information will be stored together with other information we hold such as your IP address, email content and photos you may upload to the Site and any additional information you may provide to us or which we may derive from third party sources from time to time. This information will be used by us (and our necessary service providers) to provide you with the Services and other activities associated with them. You agree that we may use your personal information as follows:</p>
          <ul>
            <li>To verify your identity and record;</li>
            <li>To facilitate our provision of the Services to you;</li>
            <li>To analyse use of the Site; and</li>
            <li>To keep you up-to-date with new features, products and other services which we think may be of interest to you.</li>
          </ul>
          <p>- We also collect, use and share Aggregated Data such as statistical or demographic data for any purpose. Aggregated Data may be derived from your personal data but is not considered personal data in law as this data does not directly or indirectly reveal your identity. For example, we may aggregate your Usage Data to calculate the percentage of users accessing a specific website feature.</p>
          <p>- We may collect Special Categories of Personal Data about you (this includes details about your race or ethnicity, religious or philosophical beliefs, sex life, sexual orientation, political opinions, trade union membership, information about your health and genetic and biometric data). We process information relating to your race in order to carry out fraud screening. We not knowingly process other Special Categories of Personal Data, but may incidentally process such data including relating to your sexual preferences if you reference such information in free text boxes in any advertisement.</p>
          <p>- We will only use your personal data for the purposes for which we collected it, unless we reasonably consider that we need to use it for another reason and that reason is compatible with the original purpose. If you wish to get an explanation as to how the processing for the new purpose is compatible with the original purpose, please contact us.If we need to use your personal data for an unrelated purpose, we will notify you and we will explain the legal basis which allows us to do so.</p>
          <p>- We will only keep your personal information for as long as necessary for the purposes for which that personal information was given to us. Please note that, in the event we sell our business to any third party, we may share your data with a prospective buyer and their advisors, and we will transfer your data to the buyer for the purposes of continuing to provide the Services to you.</p>
          <p>- Please note that, from time to time, we may transfer your personal data for internal business purposes to locations outside the European Economic Area. Whenever we transfer your personal data out of the EEA, we ensure a similar degree of protection is afforded to it by ensuring at least one of the following safeguards is implemented:</p>
          <p>- Where we use certain service providers, we may use specific contracts approved by the European Commission which give personal data the same protection it has in Europe. For further details, see European Commission: Model contracts for the transfer of personal data to third countries.</p>
          <p>- We may also disclose your personal information if required to do so by law or if we believe that disclosure is necessary to comply with any applicable law or to defend our own rights or property, or to safeguard others. This may involve disclosing the information we hold to NUM (National Ugly Mugs) or to enforcement agencies if we believe that you are using the Site to engage in criminal and/or illegal activity. NUM may also choose to disclose this information to law enforcement agencies or other security service to comply with any applicable law or if they believe doing so will safeguard others.</p>
          <p>- The Site is intended for audiences over the age of 18 and does not plan or intend to collect data from those under the age of 18. To respect the privacy of underage persons, those under the age of 18 should not provide any data on the Site.</p>
          <p>- If you have any queries about the Privacy Policy or wish to change your preferences in how we contact you about products and services, please contact us.</p>
          <p>- <b>Contact Information:</b></p>
          <ul>
            <li>Email: info@nefertarigirls.com</li>
            <li>Website: www.nefertarigirls.com</li>
          </ul>
          <p>- You can unsubscribe from our marketing emails simply clicking on the link "Unsubscribe" at the bottom of the email.</p>
          <p>- You can delete your profile from the Site anytime you want.</p>
          <p>- If you want to stop using your account temporarily, you may 'deactivate' it. Your data will be saved by us in order for you to re-access it as and when you wish to reactivate, or permanently delete, your profile. We will use reasonable endeavours to delete your data. However, even after you remove your data from your profile or delete your account, copies of your data may still be viewable and/or accessed on the internet to the extent that such data has been previously shared with others, or copied or stored by other users or to the extent that such data has been shared with search engines. We cannot control this, nor do we accept liability or responsibility for this. If you have given third party applications or website access to your personal data they may keep that data to the extent that they are allowed to under their own policies.</p>
          <p>- We have put in place appropriate security measures to prevent your personal data from being accidentally lost, used or accessed in an unauthorised way, altered or disclosed. In addition, we limit access to your personal data to those employees, agents, contractors and other third parties who have a business need to know. They will only process your personal data on our instructions and they are subject to a duty of confidentiality. We have put in place procedures to deal with any suspected personal data breach and will notify you and any applicable regulator of a breach where we are legally required to do so.</p>
          <h4>YOUR RIGHTS</h4>
          <p>- Under certain circumstances, you have rights under data protection laws in relation to your personal data. You have the right to:</p>
          <p>- <b>Request access</b> to your personal data (commonly known as a "data subject access request"). This enables you to receive a copy of the personal data we hold about you and to check that we are lawfully processing it.</p>
          <p>- <b>Request correction</b> of the personal data that we hold about you. This enables you to have any incomplete or inaccurate data we hold about you corrected, though we may need to verify the accuracy of the new data you provide to us.</p>
          <p>- <b>Request erasure</b> of your personal data. This enables you to ask us to delete or remove personal data where there is no good reason for us continuing to process it. You also have the right to ask us to delete or remove your personal data where you have successfully exercised your right to object to processing (see below), where we may have processed your information unlawfully or where we are required to erase your personal data to comply with local law. Note, however, that we may not always be able to comply with your request of erasure for specific legal reasons which will be notified to you, if applicable, at the time of your request.</p>
          <p>- <b>Object to processing</b> of your personal data where we are relying on a legitimate interest (or those of a third party) and there is something about your particular situation which makes you want to object to processing on this ground as you feel it impacts on your fundamental rights and freedoms. You also have the right to object where we are processing your personal data for direct marketing purposes. In some cases, we may demonstrate that we have compelling legitimate grounds to process your information which override your rights and freedoms.</p>
          <p>- <b>Request restriction of processing</b> of your personal data. This enables you to ask us to suspend the processing of your personal data in the following scenarios: (a) if you want us to establish the data's accuracy; (b) where our use of the data is unlawful but you do not want us to erase it; (c) where you need us to hold the data even if we no longer require it as you need it to establish, exercise or defend legal claims; or (d) you have objected to our use of your data but we need to verify whether we have overriding legitimate grounds to use it.</p>
          <p>- <b>Request the transfer</b> of your personal data to you or to a third party. We will provide to you, or a third party you have chosen, your personal data in a structured, commonly used, machine-readable format. Note that this right only applies to automated information which you initially provided consent for us to use or where we used the information to perform a contract with you.</p>
          <p>- <b>Withdraw consent</b> at any time where we are relying on consent to process your personal data. However, this will not affect the lawfulness of any processing carried out before you withdraw your consent. If you withdraw your consent, we may not be able to provide certain products or services to you. We will advise you if this is the case at the time you withdraw your consent.</p>
          <p>- If you wish to exercise any of the rights set out above, please contact us.You will not have to pay a fee to access your personal data (or to exercise any of the other rights). However, we may charge a reasonable fee if your request is clearly unfounded, repetitive or excessive. Alternatively, we may refuse to comply with your request in these circumstances.</p>
          <p>- We may need to request specific information from you to help us confirm your identity and ensure your right to access your personal data (or to exercise any of your other rights). This is a security measure to ensure that personal data is not disclosed to any person who has no right to receive it. We may also contact you to ask you for further information in relation to your request to speed up our response.</p>
          <p>- We try to respond to all legitimate requests within one month. Occasionally it may take us longer than a month if your request is particularly complex or you have made a number of requests. In this case, we will notify you and keep you updated.</p>
          <h4>COOKIES</h4>
          <p>- Please note that we may use 'cookies' while you access the Site to avoid the need to re-enter details on different occasions and other such purposes. If you do not wish to receive 'cookies', you may change the settings on your computer or browser accordingly.</p>
          <h5>What are Cookies?</h5>
          <p>- A cookie is a small file containing information that is sent to your computer when you visit a website. When returning to the website, the cookie allows that site to recognise your browser and permits automation on signing in and registration of information so that the Site is adjusted to your preferences and promotions and marketing are personalised to you. Cookies can store user preferences and other information in order to provide you with a better, faster and safer experience. The use of Cookies permits us to track the use of the Site so that we can improve it. This tracking is never done at individual level and is always done in isolation from your specific identity.</p>
          <h5>Use of cookies by nefertarigirls.com</h5>
          <p>- We use cookies to help identify you and maintain your signed-in status. They also assist us in diagnosing problems with our server, and to administer the Site.</p>
          <p>- Most cookies are "session cookies", meaning that they are automatically deleted from your hard drive at the end of a session. Please see 2.3 below.</p>
          <p>- If you do not want to reveal the details of your demographics location or other non-identity specific information, you can remove or block cookies using the settings in your browser. Please note but in some cases, this may impact your ability to use nefertarigirls.com and its full range of services.</p>
          <p>- You may encounter cookies from third parties on certain pages of the sites that we do not control. (For example, if you view a web page created by another user, there may be a cookie placed by that web page). nefertarigirls.com is not responsible for the content on other third party sites nor is it responsible for how information is collected on or by those sites.</p>
          <p>To find out more about cookies visit www.allaboutcookies.org</p>
          <h5>What is a session cookie?</h5>
          <p>- A session cookie is a temporary file, which is deleted when you close your browser.</p>
          <p>- The next time you open your browser and go back to the site that created the cookie the website will not recognise you, forcing you to log back in (if login is required) or select your preferences/themes again if the site uses these features.</p>
          <p>- A new session cookie is then generated, which will store your browsing information until you leave the site and close your browser.</p>
          <p>- Session cookies do not collect information from the user's computer.</p>
          <h4>PAYMENT</h4>
          <p>We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).</p>
          <p>We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
          <p>The payment processors we work with are:</p>
          <p><a href=" https://www.paysafe.com/legal-and-compliance/privacy-policy/">Paysafecard.com</a></p>
          <h4>LINKS TO OTHER SITES</h4>
          <p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
          <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
          <h4>CONSENT</h4>
          <p>- By using our website, you consent to the collection and use of your IP details, personal information and location data in accordance with this policy. If we change our Privacy Policy at any time, these changes will be reflected here, so please regularly check this policy to ensure you are aware of any updates.</p>        
        </div>
      </div>
  	</section>
    <?php include 'inc/modals.php' ?>
    <?php include 'inc/footer.php' ?>
    <?php include 'inc/scripts.php' ?>
  </body>
</html>